### ISSUE TITLE
Preserve original licence text

### ISSUE THREAD

**Issue by ChrisBeeley** [nhs-r-community/ISR-iterative-sequential-regression-#6]
The MIT licence stipulates that we preserve the original licence text from the package in any derivatvive works. Add this in to the package https://github.com/ischlackow/ISR-iterative-sequential-regression-/blob/main/LICENSE

**Comment by Lextuga007** [comment]
My misunderstanding - I'll replace it.

**Comment by Lextuga007** [comment]
Just to check does the LICENCE document (that didn't exist in the original) also say 2022 ischlackow? Currently defaults to isr authors when I use usethis.
